/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifrn.tads.arkanoid.gui;

import br.ifrn.tads.arkanoid.jogo.ControleDeJogo;
/**
 *
 * @author Júnior Lucena
 */
public class fimDeJogo extends javax.swing.JPanel {
    ControleDeJogo jogo;
    /**
     * Creates new form fimDeJogo
     */
    public fimDeJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void botaoNaoActionPerformed(java.awt.event.ActionEvent evt) {
        jogo.TerminarJogo();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgFimDeJogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botSim = new javax.swing.JLabel();
        botaoSim = new javax.swing.JButton();
        botNao = new javax.swing.JLabel();
        botaoNao = new javax.swing.JButton();
        imgTelaInicial = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msgFimDeJogo.setFont(new java.awt.Font("Verdana", 1, 70)); // NOI18N
        msgFimDeJogo.setForeground(new java.awt.Color(250, 9, 9));
        msgFimDeJogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgFimDeJogo.setText("Fim De Jogo!!!");
        add(msgFimDeJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 650, 170));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Deseja Jogar Novamente?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        botSim.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botSim.setText("SIM");
        add(botSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 426, 80, -1));

        botaoSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ifrn/tads/arkanoid/imagens/Buttons.jpg"))); // NOI18N
        botaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSimActionPerformed(evt);
            }
        });
        add(botaoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 220, 60));
        botaoSim.getAccessibleContext().setAccessibleName("butonSim");

        botNao.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        botNao.setText("Não");
        add(botNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 424, -1, 50));

        botaoNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ifrn/tads/arkanoid/imagens/Buttons.jpg"))); // NOI18N
        add(botaoNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 220, 60));

        imgTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ifrn/tads/arkanoid/imagens/papel-de-parede.jpg"))); // NOI18N
        imgTelaInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        add(imgTelaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 539));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSimActionPerformed
      jogo.IniciarJogo();
    }//GEN-LAST:event_botaoSimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botNao;
    private javax.swing.JLabel botSim;
    private javax.swing.JButton botaoNao;
    private javax.swing.JButton botaoSim;
    private javax.swing.JLabel imgTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel msgFimDeJogo;
    // End of variables declaration//GEN-END:variables
}
